import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

const removeProps = (obj: Object, props: string[]) => {
    const newObj = { ...obj }
            console.log(obj, props)

    for (let prop of props) {
      delete newObj[prop]
    }
    console.log(newObj)
    return newObj;
}

export const useQueryParamsRemover = (...params: string[]) => {
  const router = useRouter()

  useEffect(() => {
    const { pathname, query } = router
    console.log(1, router, params);
    // if (!params.length) {
    //   router.replace({ pathname, query: {} }, undefined, { shallow: true })
    //   return
    // }
    // console.log(query)
    // const newQuery = removeProps(query, params);
    // router.replace({ pathname, query: newQuery }, undefined, { shallow: true })
  }, [])
}


const Home: NextPage = () => {
    useQueryParamsRemover('a', 'b')
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
        <h1 className={styles.title}>useQueryParamsRemover</h1>
    </main>
    </div>
  )
}

export default Home

export const getServersideProps = () => {
    return {
        props: null,
    }
}
